INIT

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -3,37 +3,63 @@
 # https://docs.microsoft.com/azure/devops/pipelines/languages/docker
 
 trigger:
-- main
+  - main
 
 resources:
-- repo: self
+  - repo: self
 
 variables:
   # Container registry service connection established during pipeline creation
-  dockerRegistryServiceConnection: '25606b51-17d8-40c6-b84d-cb58c8d795ea'
-  imageRepository: 'trnnodedemodocker'
-  containerRegistry: 'mentorklubacr.azurecr.io'
-  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
-  tag: '$(Build.BuildId)'
+  dockerRegistryServiceConnection: "25606b51-17d8-40c6-b84d-cb58c8d795ea"
+  imageRepository: "trnnodedemodocker"
+  containerRegistry: "mentorklubacr.azurecr.io"
+  dockerfilePath: "$(Build.SourcesDirectory)/Dockerfile"
+  tag: "$(Build.BuildId)"
 
   # Agent VM image name
-  vmImageName: 'ubuntu-latest'
+  vmImageName: "ubuntu-latest"
 
 stages:
-- stage: Build
-  displayName: Build and push stage
-  jobs:
-  - job: Build
-    displayName: Build
-    pool:
-      vmImage: $(vmImageName)
-    steps:
-    - task: Docker@2
-      displayName: Build and push an image to container registry
-      inputs:
-        command: buildAndPush
-        repository: $(imageRepository)
-        dockerfile: $(dockerfilePath)
-        containerRegistry: $(dockerRegistryServiceConnection)
-        tags: |
-          $(tag)
+  - stage: ci_code_check
+    displayName: CI - Kód ellenőrzés
+    condition: eq(variables['Build.Reason'], 'PullRequest')
+    jobs:
+      - job: basic_check
+        displayName: Alap ellenőrzés
+        steps:
+          - task: NodeTool@0
+            inputs:
+              versionSpec: "18.x"
+            displayName: "Install Node.js"
+          - script: |
+              sudo npm install
+              sudo npm install eslint  
+
+              echo "##[command]A kód rendben?"
+              sudo npm run test
+              commandresult=$(echo $?)    
+              echo "##[debug]Kód ellenőrzés eredménye: $commandresult"
+              if [[ $commandresult != 0 ]];
+              then
+                echo "##vso[task.complete result=Failed;]A kódban hiba található!"
+              fi
+            displayName: "Kód ellenőrzés"
+  - stage: Build
+    displayName: CD - Build and push stage
+    condition: eq(variables['Build.reason'], 'IndividualCI')
+    jobs:
+      - job: Build
+        displayName: Build
+        pool:
+          vmImage: $(vmImageName)
+        steps:
+          - task: Docker@2
+            displayName: Build and push an image to container registry
+            inputs:
+              command: buildAndPush
+              repository: $(imageRepository)
+              dockerfile: $(dockerfilePath)
+              containerRegistry: $(dockerRegistryServiceConnection)
+              tags: |
+                $(tag)
+                latest
